# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c09602df8b724eff170f4947b70f3a734dbbf7f28230aba4d21bece6d6f887b67803c72c4e225bfb56913a9f623268acbd294f26ad79a3389f1acc8c9180d159

test:
  secret_key_base: 77d444fd56e6011c58eee009e6d1ec1ac7ced8c7ded244278a3e624c688eae1a52cc45e28c6f0a818b530fd6ae69629460f30a8ab6640c651bd41b253fdc583a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
